# A small k3s cluster on one Proxmox node: 1 server (control-plane) + N agents.
# Terraform creates the VMs from an Ubuntu cloud image; Ansible installs k3s on top.

locals {
  # One flat map so master and workers share a single VM resource.
  nodes = merge(
    {
      (var.master.name) = {
        vm_id       = var.master.vm_id
        ip          = var.master.ip
        mac_address = var.master.mac_address
        memory_mb   = coalesce(var.master.memory_mb, var.memory_mb)
        role        = "server"
      }
    },
    {
      for w in var.workers : w.name => {
        vm_id       = w.vm_id
        ip          = w.ip
        mac_address = w.mac_address
        memory_mb   = coalesce(w.memory_mb, var.memory_mb)
        role        = "agent"
      }
    },
  )

  dns_servers = var.dns_servers != null ? var.dns_servers : [var.gateway_ip]

  ansible_dir    = "${path.module}/../../ansible"
  inventory_path = "${path.module}/../../ansible/inventory/${var.cluster_name}.ini"
  private_key    = pathexpand(var.ssh_key_path)

  # Re-run Ansible whenever the playbook or any k3s role file changes,
  # without recreating the VMs.
  ansible_files = sort(concat(
    [for f in fileset(local.ansible_dir, "k3s.yml") : f],
    [for f in fileset(local.ansible_dir, "roles/k3s_*/**") : f],
  ))
  ansible_fingerprint = sha256(join("", [for f in local.ansible_files : filesha256("${local.ansible_dir}/${f}")]))
}

# Ubuntu cloud image, downloaded once onto the node and reused as the disk of every VM.
resource "proxmox_virtual_environment_download_file" "cloud_image" {
  content_type = "iso"
  datastore_id = var.image_datastore
  node_name    = var.proxmox_node
  url          = var.image_url
  file_name    = var.image_file_name
  overwrite    = false
}

resource "proxmox_virtual_environment_vm" "node" {
  for_each = local.nodes

  name        = each.key
  description = "k3s ${each.value.role} node (managed by Terraform)"
  tags        = [var.cluster_name, each.value.role]

  node_name = var.proxmox_node
  vm_id     = each.value.vm_id

  on_boot         = true
  stop_on_destroy = true

  # Enabled only after Ansible has installed qemu-guest-agent — otherwise
  # Terraform waits for an agent that does not answer yet.
  agent {
    enabled = var.qemu_agent_enabled
  }

  cpu {
    cores = var.cpu_cores
    type  = var.cpu_type
  }

  memory {
    dedicated = each.value.memory_mb
  }

  disk {
    datastore_id = var.disk_datastore
    file_id      = proxmox_virtual_environment_download_file.cloud_image.id
    interface    = "scsi0"
    size         = var.disk_size
    discard      = "on"
    ssd          = true
  }

  initialization {
    datastore_id = var.disk_datastore

    ip_config {
      ipv4 {
        address = "${each.value.ip}/${var.network_cidr}"
        gateway = var.gateway_ip
      }
    }

    dns {
      servers = local.dns_servers
    }

    user_account {
      username = var.vm_username
      keys     = var.ssh_public_keys
    }
  }

  network_device {
    bridge = var.network_bridge
    # Pinned so the router's DHCP reservation / internet policy survives a recreate.
    mac_address = each.value.mac_address
  }

  operating_system {
    type = "l26"
  }

  # Cloud images expect a serial console.
  serial_device {}
}

# Inventory for the Ansible run below; also handy for running the playbook by hand.
resource "local_file" "inventory" {
  filename        = local.inventory_path
  file_permission = "0644"

  content = <<-EOT
    # Generated by Terraform (modules/k3s_cluster) — do not edit by hand.
    [k3s_master]
    ${var.master.name} ansible_host=${var.master.ip}

    [k3s_workers]
    ${join("\n", [for w in var.workers : "${w.name} ansible_host=${w.ip}"])}

    [k3s:children]
    k3s_master
    k3s_workers

    [k3s:vars]
    ansible_user=${var.vm_username}
    ansible_ssh_private_key_file=${local.private_key}
    ansible_python_interpreter=/usr/bin/python3
    ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  EOT
}

# Wait until cloud-init has finished on every VM before Ansible touches them.
resource "terraform_data" "wait_for_cloud_init" {
  for_each = local.nodes

  triggers_replace = [proxmox_virtual_environment_vm.node[each.key].id]

  provisioner "remote-exec" {
    inline = [
      "cloud-init status --wait || true",
      "echo '${each.key} is ready'",
    ]

    connection {
      type        = "ssh"
      user        = var.vm_username
      private_key = file(local.private_key)
      host        = each.value.ip
      timeout     = "10m"
    }
  }
}

# Installing k3s is a separate resource so editing the roles re-runs Ansible
# without recreating any VM.
resource "terraform_data" "install_k3s" {
  depends_on = [terraform_data.wait_for_cloud_init, local_file.inventory]

  triggers_replace = [
    join(",", [for name in sort(keys(local.nodes)) : proxmox_virtual_environment_vm.node[name].id]),
    local.ansible_fingerprint,
    local_file.inventory.content,
    var.k3s_channel,
    var.k3s_version,
    jsonencode(var.k3s_server_args),
    jsonencode(var.k3s_agent_args),
    var.kubeconfig_local_path,
  ]

  provisioner "local-exec" {
    command = <<-EOT
      export ANSIBLE_HOST_KEY_CHECKING=False
      ansible-playbook -i '${local.inventory_path}' \
        -e '${jsonencode({
    k3s_channel           = var.k3s_channel
    k3s_version           = var.k3s_version
    k3s_server_args       = var.k3s_server_args
    k3s_agent_args        = var.k3s_agent_args
    k3s_master_ip         = var.master.ip
    kubeconfig_local_path = var.kubeconfig_local_path
})}' \
        ${local.ansible_dir}/k3s.yml
    EOT
}
}
